### ISSUE TITLE
Fails to build with TBB 2021.5.0

### ISSUE THREAD

**Issue by merkys** [medvedevgroup/TwoPaCo#28]
I am building TwoPaCo 0.9.4 with TBB 2021.5.0 on Debian experimental. The build fails with the following:
```
In file included from /home/merkys/twopaco/src/graphdump/graphdump.cpp:17:
/home/merkys/twopaco/src/graphdump/../common/streamfastaparser.h:8:10: fatal error: tbb/mutex.h: No such file or directory
    8 | #include <tbb/mutex.h>
      |          ^~~~~~~~~~~~~
```
Does this mean that TwoPaCo does not support TBB 2021.5.0? If so, are there plans to support it?

**Comment by merkys** [comment]
I see, thanks for the explanation.

**Comment by tillea** [comment]
Just for the sake of interest:  In Debian we try to create separate packages from separate projects.  While our final target is salmon which in turn uses pufferfish which is using twopaco we started with twopaco to use this in a pufferfish Debian package.  It seems the twopaco code in pufferfish is not the same as upstream twopaco and our way to tackle a pufferfish package is not the best idea in this case, right?
Kind regards, Andreas.

**Comment by rob-p** [comment]
Hi @tillea — this is correct.  The vendored version of TwoPaCo in pufferfish has updates that have not been ported upstream that, among other things, allow it to use the newer versions of OneTBB.  The other major change is just turning TwoPaCo into an easier-to-use CMake module.  If those changes got pushed upstream, we'd be happy to rely on an upstream TwoPaCo, but we don't currently have the cycles for that right now.
